server:
  port: 8801

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hmall?useSSL=false&serverTimezone=UTC
    username: root
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

  main:
    allow-circular-references: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
